service: basic-next-serverless-app

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512

stage: dev
region: eu-west-1

plugins:
  - "thrive-serverless-plugin"
  - serverless-offline

custom:
  serverless-nextjs:
    routes:
      - src: post
        path: post/{slug}
        request:
          parameters:
            paths:
              slug: true

package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**
